spring.application.name=event

# Server Port
# Student is 8081, Faculty is 8082, so Event is 8083
server.port=8083

# JWT Configuration
# This MUST be the same secret string used in the Student service
jwt.secret=MySecretKeyForJWTSigning12345678901234567890